cols_to_drop_accuri:
- Time
cols_to_drop_cytoflex:
- Time
fc_type: Accuri
gating_type: Line
autoencoder: ae_accuri_13.h5
mse_threshold: -1
hardware: GPU
lr: 1e-5
lr_reduced: 1e-3
lr_scheduler: Time Decay
model: classifier_14_512.h5
num_batches: 512
num_classes: 11
num_epochs: 100
num_features: 14
num_umap_cores: 8
results: /Users/v_vlsv/PyCharmProjects/CellScanner/CellScanner_1.2.0/outputs
vis_channels_accuri:
- FL1-A
- FL2-A
- FL3-A
vis_channels_cytoflex:
- FSC-H
- FSC-A
- SSC-H
vis_dims: 3D
vis_type: UMAP
