autoencoder: ae_accuri_13.h5
cols_to_drop_accuri:
- Time
cols_to_drop_cytoflex:
- Time
fc_type: Accuri
gating_type: Autoencoder
hardware: GPU
lr: 1e-5
lr_scheduler: Constant
model: test_bt_bi_ec.h5
mse_threshold: 0.05
num_batches: 512
num_classes: 11
num_epochs: 5
num_umap_cores: 8
results: /Users/v_vlsv/PyCharmProjects/CellScanner/CellScanner_1.2.0/outputs
vis_channels_accuri:
- FL1-A
- FL2-A
- FL3-A
vis_channels_cytoflex:
- FSC-H
- FSC-A
- SSC-H
vis_dims: '3'
vis_type: Channels
