fc_type: Accuri
gating_type: Line
hardware: GPU
lr: 1e-5
lr_reduced: 1e-2
lr_scheduler: Constant
model: classifier_14_512.h5
num_batches: 256
num_classes: 11
num_epochs: 10
num_features: 14
num_umap_cores: 8
results: /Users/v_vlsv/PyCharmProjects/CellScanner/CellScanner_1.2.0/outputs
vis_channels: Bla-1
vis_dims: 3D
vis_type: UMAP
