autoencoder: ae.h5
blank_threshold: 5
cols_to_drop_accuri:
- Time
cols_to_drop_cytoflex:
- Time
fc_type: Accuri
gating_type: Autoencoder
hardware: GPU
lr: 1e-5
lr_scheduler: Time Decay
mlp: false
model: 515_1315_avg.h5
mse_threshold: 10.0
num_batches: 256
num_epochs: 50
num_umap_cores: 8
number_of_clusters: 10
results: /Users/v_vlsv/PyCharmProjects/CellScanner/CellScanner_1.2.0/outputs
softmax_prob_threshold: 0.9
vis_channels_accuri:
- FL2-A
- SSC-H
- FL2-H
vis_channels_cytoflex:
- FSC-H
- FSC-A
- SSC-H
vis_dims: 3
vis_type: Channels
