autoencoder: ae.h5
blank_threshold: 5
cols_to_drop_accuri:
  - Time
cols_to_drop_cytoflex:
  - Time
fc_type: Accuri
gating_type: Autoencoder
hardware: GPU
lr: 1e-3
lr_scheduler: Step Decay
mlp: false
model: ba_ec_pm.h5
mse_threshold: 0.5
num_batches: 256
num_epochs: 50
num_umap_cores: 4
number_of_clusters: 10
results: ./outputs
softmax_prob_threshold: 0.9
vis_channels_accuri:
  - FSC-A
  - SSC-A
  - SSC-H
vis_channels_cytoflex:
  - FSC-A
  - SSC-H
  - SSC-A
vis_dims: 3
vis_type: Channels
